# Generated by Django 5.1.6 on 2025-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
