# Generated by Django 5.1.6 on 2025-03-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0002_alter_trainee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
